"""Core analytics interfaces, context types, exceptions, and models."""

from app.analytics.core.types import (
    PeriodGranularity,
    TrendDirection,
    MetricUnit,
    CorrelationMethod,
    HypothesisTestType,
    SortOrder,
)
from app.analytics.core.exceptions import (
    AnalyticsError,
    InsufficientDataError,
    InvalidContextError,
    UndefinedMetricError,
    DecompositionError,
)
from app.analytics.core.context import AnalysisContext
from app.analytics.core.models import (
    MetricValue,
    ComparisonResult,
    BreakdownItem,
    BreakdownResult,
    TimeSeriesPoint,
    TimeSeriesResult,
    FinancialSummaryResult,
    ProductPerformanceItem,
    CustomerRFMRecord,
    CohortCell,
    CohortRow,
    RepeatPurchaseResult,
    PriceVolumeMixDecomposition,
    VarianceContributor,
    VarianceAnalysisResult,
    StatisticalTestResult,
    CorrelationResult,
)

__all__ = [
    "PeriodGranularity",
    "TrendDirection",
    "MetricUnit",
    "CorrelationMethod",
    "HypothesisTestType",
    "SortOrder",
    "AnalyticsError",
    "InsufficientDataError",
    "InvalidContextError",
    "UndefinedMetricError",
    "DecompositionError",
    "AnalysisContext",
    "MetricValue",
    "ComparisonResult",
    "BreakdownItem",
    "BreakdownResult",
    "TimeSeriesPoint",
    "TimeSeriesResult",
    "FinancialSummaryResult",
    "ProductPerformanceItem",
    "CustomerRFMRecord",
    "CohortCell",
    "CohortRow",
    "RepeatPurchaseResult",
    "PriceVolumeMixDecomposition",
    "VarianceContributor",
    "VarianceAnalysisResult",
    "StatisticalTestResult",
    "CorrelationResult",
]
